        //    ---Datas--    //--//
const bossInfos = [
    foolsInfos = {
      nome:       'Fools',
      nick:       'Fools113',
      tipo:       'Administrador',
      doc:        'fools_infos',
      boss_link:  'https://rockeydoggy.github.io/#Fools',
      avatar_url: 'https://i.imgur.com/DkWSra6.png',
      boss_banner:'https://i.imgur.com/PpHVeZ2.png',
      classe:     'roxoLvl',
      asda:       'FoolsStory',
      extra1:     '',
      status: {
        vida:         3400,
        resistencia:  1000,
        resiliencia:  0,
        força:        1000,
        foco:         60,
        agilidade:    2,
      },
      index: 0,
    },
    juninhoInfos = {
      nome:       'Juninho',
      nick:       'rGreque',
      tipo:       'BOSS',
      doc:        'juninho_infos',
      boss_link:  'https://rockeydoggy.github.io/#Junin',
      avatar_url: 'https://i.imgur.com/HNFcmhV.png',
      boss_banner:'https://i.imgur.com/UjzWIes.png',
      classe:     'roxoLvl',
      extra1: '',
      status: {
        vida:         1000,
        resistencia:  1000,
        resiliencia:  0,
        força:        1000,
        foco:         5,
        agilidade:    1,
      },
      index: 1,
    },
    sirkingInfos = {
      nome:       'Sir King',
      nick:       'S1rKing',
      tipo:       'BOSS',
      doc:        'king_infos',
      boss_link:  'https://rockeydoggy.github.io/#Kingo',
      avatar_url: 'https://i.imgur.com/2MK2dvP.png',
      boss_banner:'https://i.imgur.com/C8bdCDJ.png',
      classe:     'roxoLvl',
      extra1: '',
      status: {
        vida:         73,
        resistencia:  10,
        resiliencia:  10,
        força:        70,
        foco:         8,
        agilidade:    1,
      },
      index: 2,
    },
    pandasInfos = {
      nome:       'Pandas',
      nick:       'Pandas_S2',
      tipo:       'BOSS',
      doc:        'pandas_infos',
      boss_link:  'https://rockeydoggy.github.io/#Pandas',
      avatar_url: 'https://i.imgur.com/s5tL7wT.png',
      boss_banner:'https://i.imgur.com/kLIT76F.png',
      classe:     'roxoLvl',
      extra1: '',
      status: {
        vida:         100,
        resistencia:  100,
        resiliencia:  0,
        força:        100,
        foco:         7,
        agilidade:    1,
      },
      index: 3,
    },
    guiInfos = {
      nome:       'Gui',
      nick:       'godiira',
      tipo:       'BOSS',
      doc:        'gui_infos',
      boss_link:  'https://rockeydoggy.github.io/#Gui',
      avatar_url: '',
      boss_banner:'',
      classe:     'roxoLvl',
      extra1: '',
      status: {
        vida:         100,
        resistencia:  100,
        resiliencia:  0,
        força:        100,
        foco:         7,
        agilidade:    1,
      },
      index: 4,
    },
    eddyInfos = {
      nome:       'Edney',
      nick:       'edney_de_pijama',
      tipo:       'BOSS',
      doc:        'eddy_infos',
      boss_link:  'https://rockeydoggy.github.io/#Gui',
      avatar_url: '',
      boss_banner:'',
      classe:     'roxoLvl',
      extra1: '',
      status: {
        vida:         1852,
        resistencia:  759,
        resiliencia:  741,
        força:        759,
        foco:         8,
        agilidade:    1,
      },
      index: 5,
    },
  ]
  const extraBossInfos = [
    sbeekerInfos = {
      nome:       'Sbeeker',
      nick:       'Sbevee_ / snekerroyal',
      tipo:       'BOSS',
      doc:        'sbeeker_infos',
      boss_link:  'https://rockeydoggy.github.io/#Sbeeker',
      avatar_url: 'https://i.imgur.com/0vN6YKB.png',
      boss_banner:'https://i.imgur.com/fKw0EZY.png',
      classe:     'amareloLvl',
      extra1: '',
      status: {
        vida:         0,
        resistencia:  50,
        resiliencia:  0,
        força:        23,
        foco:         0,
        agilidade:    0,
      },
      index: 0,
    },
    steveInfos = {
      nome:       'Steve',
      nick:       'sbevee_',
      tipo:       'Administrador',
      doc:        'steve_infos',
      boss_link:  'https://rockeydoggy.github.io/#Steve',
      avatar_url: 'https://i.imgur.com/9nIbTe2.png',
      boss_banner:'https://i.imgur.com/jpqYsWu.png',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         4,
        resistencia:  3,
        resiliencia:  0,
        força:        3,
        foco:         0,
        agilidade:    0,
      },
      index: 1,
    },
    rafaInfos = {
      nome:       'Rafa',
      nick:       'RafaaSmile',
      tipo:       'Visitante',
      doc:        'rafa_infos',
      boss_link:  'https://rockeydoggy.github.io/#Rafa',
      avatar_url: 'https://i.imgur.com/gNcv5M8.png',
      boss_banner:'https://i.imgur.com/kBZCmgi.png',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         0,
        resistencia:  0,
        resiliencia:  0,
        força:        0,
        foco:         0,
        agilidade:    0,
      },
      index: 2,
    },
    draxyInfos = {
      nome:       'Mandrax',
      nick:       'Draaaxxy',
      tipo:       'Visitante',
      doc:        'mandrax_infos',
      boss_link:  'https://rockeydoggy.github.io/#Mandrax',
      avatar_url: 'https://i.imgur.com/Zr4V0lv.png',
      boss_banner:'https://i.imgur.com/aIIr053.png',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         5,
        resistencia:  5,
        resiliencia:  0,
        força:        5,
        foco:         0,
        agilidade:    0,
      },
      index: 3,
    },
    girlInfos = {
      nome:       'Girl',
      nick:       'little_bunbunny',
      tipo:       'Visitante',
      doc:        'girl_infos',
      boss_link:  'https://rockeydoggy.github.io/#Girl',
      avatar_url: 'https://i.imgur.com/aBCpLbS.png',
      boss_banner:'https://i.imgur.com/nWLUjQw.png',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         438,
        resistencia:  10,
        resiliencia:  0,
        força:        10,
        foco:         0,
        agilidade:    0,
      },
      index: 4,
    },
    whityInfos = {
      nome:       'Whity',
      nick:       'WhityKun_',
      tipo:       'Visitante',
      doc:        'whity_infos',
      boss_link:  'https://rockeydoggy.github.io/#Whity',
      avatar_url: 'https://i.imgur.com/PMlH1Le.png',
      boss_banner:'https://i.imgur.com/AjINP7o.png',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         9,
        resistencia:  8,
        resiliencia:  0,
        força:        8,
        foco:         0,
        agilidade:    0,
      },
      index: 5,
    },
    kingaInfos = {
      nome:       'Kinga',
      nick:       'Kinguinha',
      tipo:       'Visitante',
      doc:        'kinga_infos',
      boss_link:  'https://rockeydoggy.github.io/#kinga',
      avatar_url: '',
      boss_banner:'',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         22,
        resistencia:  20,
        resiliencia:  0,
        força:        20,
        foco:         3,
        agilidade:    0,
      },
      index: 6,
    },
    pauloInfos = {
      nome:       'Paulo',
      nick:       'paulohenrique82_',
      tipo:       'Visitante',
      doc:        'paulo_infos',
      boss_link:  'https://rockeydoggy.github.io/#Paulus',
      avatar_url: '',
      boss_banner:'',
      classe:     'greyLvl',
      extra1: '',
      status: {
        vida:         524,
        resistencia:  100,
        resiliencia:  0,
        força:        100,
        foco:         0,
        agilidade:    0,
      },
      index: 7,
    },
  ]
